name: ithreve_web
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  path: ^1.9.0
  intl: ^0.19.0
  dio: ^5.2.1+1
  get_it: ^7.7.0
  file_picker: ^8.0.5
  flutter_svg: ^2.0.7
  after_layout: ^1.2.0
  flutter_bloc: ^8.0.0
  flutter_lorem: ^2.0.0
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.8
  json_annotation: ^4.7.0
  pin_code_fields: ^8.0.1
  connectivity_plus: ^4.0.1
  intl_phone_number_input: ^0.7.4
  retrofit: ^4.2.0
  dartz: ^0.10.1
  injectable: ^2.4.4
  pretty_dio_logger: ^1.4.0
  visibility_detector: ^0.4.0+2
  easy_localization: ^3.0.7
  beamer: ^1.6.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.2.7



  

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1
  injectable_generator: ^2.6.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vector/logo/
    - assets/vector/arrow/
    - assets/vector/fields/
    - assets/vector/side_menu/
    - assets/vector/
    - assets/raster/
    - assets/fonts/
    - assets/translations/
    - assets/

  fonts:
    - family: SFProDisplay-RegularItalic
      fonts:
        - asset: assets/fonts/SFProDisplay-RegularItalic.ttf
    - family: SFProDisplay-Regular
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
